GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjMiLCJpZCI6IjYzZDI3NmQ5OTMxOTYyNzAyNjk0OGM0MSIsImlhdCI6MTY3NTAyODk4OCwiZXhwIjoxNjc1MDMyNTg4fQ.FPGu-LU5zi9--komWZvdwLfF1J0cGwID0_KWTKosPaU
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjMiLCJpZCI6IjYzZDI3NmQ5OTMxOTYyNzAyNjk0OGM0MSIsImlhdCI6MTY3NTAyODk4OCwiZXhwIjoxNjc1MDMyNTg4fQ.FPGu-LU5zi9--komWZvdwLfF1J0cGwID0_KWTKosPaU
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYzZDI3NTM5ZmI3MDI1MTRmNjYwMmY0ZiIsImlhdCI6MTY3NTAyNjQ3MywiZXhwIjoxNjc1MDMwMDczfQ.lKQ-cyw6Mk2Whf9SyjWR9ClhjZiYdqU97syP0ydjnf0
