GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYzZDI3NTM5ZmI3MDI1MTRmNjYwMmY0ZiIsImlhdCI6MTY3NDgwNzI2OSwiZXhwIjoxNjc0ODEwODY5fQ.Gi6KOEtSF3zhAA9L3WrWU6_do4mVk5mV0eIoknCUnfU
