POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjMiLCJpZCI6IjYzZDI3NmQ5OTMxOTYyNzAyNjk0OGM0MSIsImlhdCI6MTY3NTAzMTc5OSwiZXhwIjoxNjc1MDM1Mzk5fQ.-UF6ld0iYKDzYJlhsAzxFEYmkDUyBgORbsNnx1wSpX4

{
    "title": "after user middleware",
    "author": "dev3",
    "url": "https://cnn.com",
    "likes": "300470",
    "userId": "63d276d99319627026948c41"
}
